project:
  type: website
  output-dir: docs
  preview:
    port: 3333

website:
  title: "MUSA 550 Final Project"
  page-footer:
    left: "Wei Jing Ang, 2024"
    right: "This page is built with ❤️ and [Quarto](https://quarto.org/)."

  sidebar:
    logo: "images/icon.png"
    pinned: true
    align: center
    tools:
      - icon: mortarboard-fill
        href: https://scholar.google.com/citations?user=uX6hQK4AAAAJ&hl=en&authuser=1&oi=ao
        text: "Google Scholar"
      - icon: linkedin
        href: https://www.linkedin.com/in/wei-jing-ang/
        text: "LinkedIn"
      - icon: github
        href: https://github.com/weijingg
        text: "GitHub"
    style: "docked"
    search: true
    collapse-level: 2
    contents:
      - href: index.qmd
        text: Introduction
      - about.qmd
      - section: analysis/index.qmd
        contents:
          - analysis/1-IF.qmd 
          - analysis/2-Wetland.qmd
          - analysis/3-Bathymetry.qmd

format:
  html:
    highlight-style: solarized
    theme: 
    - cosmo
    - custom.scss
    css: styles.css
    code-copy: true
    code-overflow: wrap
    toc: true
